### ISSUE TITLE
Throws error for twitter account with no images

### ISSUE THREAD

**Issue by ayshimz** [ZhuyuLee/EC_601#2]
Program throws 'list index out of range error' with handle with no images. Consider try catch statements for future use.
![coderev1](https://user-images.githubusercontent.com/23141699/45959695-7faa8680-bfe8-11e8-94eb-12db04465f4a.JPG)

**Comment by ZhuyuLICFC** [comment]
Really really thank you for pointing out this issue, I will fix it and update the readme file
